### ISSUE TITLE
[Ticketer] Multiple ticket manager roles

### ISSUE THREAD

**Issue by Jademalo** [Dav-Git/Dav-Cogs#100]
I'm trying to set the ticket cog up in my server, however I'm having an issue that I'm not sure how to solve.

In our role hierachy, the bot rank is a lower rank than our mod rank. This means that whenever a new ticket is created with the mod role being the ticket manager role, the bot is unable to see the newly created channel. 
This throws an error, and makes the cog entirely unusable.
We don't really want to make a ticket manager role to prevent clutter and keep things simple, but we also don't want to give the bot the full mod role.

From what I can see, a simple fix would be to allow for more than one ticket manager role, adding the bot role in addition to the mod role. Would that be a reasonable addition?

Thanks!

**Comment by Dav-Git** [comment]
Ticketer has reached EOL.
