### ISSUE TITLE
[nicknamer] feature - role based nickname prefixes

### ISSUE THREAD

**Issue by CruxCraft** [Dav-Git/Dav-Cogs#101]
Might it be possible for you to set it up so that nicknames can have prefixes that are role based?

We run a gaming server that uses prefixes for factions, and it would be neat if when someone joins a faction they get their prefix [XYZ] automatically. Just a thought if you have time xD

**Comment by Dav-Git** [comment]
This isn't really a commonly required feature.
Roles are specifically a tool to group members into different categories (like factions).
Having a name prefix additionally to the role, would just be redundant display of the same information.
