### ISSUE TITLE
Suggestion/Request anonreporter cog

### ISSUE THREAD

**Issue by theMisteryDE** [Dav-Git/Dav-Cogs#110]
**Is your feature request related to a problem? Please describe.**
I tried out the anonreporter cog as a replacement for Jintaku's confession cog  (https://github.com/Jintaku/Jintaku-Cogs-V3)
While testing I realised that it is not really anonym, since I can see who made the report command and knowing you have only 120 seconds, you could figure it out really easy.

**Describe the solution you'd like**
Enable the report command in DM's so you can avoid obvious command in an Server and the really short time to type.

**Describe alternatives you've considered**
I would really like to see this cog in a functional way, like confession was. "[p]command text" and if the Bot is on multiple Servers with a Report Channel and the User as well, it asks for which of the overlapping Servers it should use.

**Additional context**
My Bot supports 30 Servers, one is very active and used the confession command as some kind of anonym therapy group?! The Text is most of the time more, than one can actually type in 120 seconds. I would really like to give them back this way of helping each other.

**Comment by Dav-Git** [comment]
This has been introduced in [049790c](https://github.com/Dav-Git/Dav-Cogs/commit/049790c31b5b7dbf792bf49ea5285fe3ec446100)
