### ISSUE TITLE
Check doesn't show warnings from Warnings cog

### ISSUE THREAD

**Issue by jriggz** [Dav-Git/Dav-Cogs#113]
**Describe the bug**
"Check" does not show output other than what "userinfo" provides.

**To Reproduce**
1. Use Warnings as your warning cog
2. Have Check installed
3. "check" a user with known warnings on record (.check UID or username)
4. Only Userinfo is displayed

**Expected behavior**
When using Check I expect it to behave as described and choose between cogs to successfully display information such as warnings.

**Screenshots**
![image](https://github.com/Dav-Git/Dav-Cogs/assets/16052932/538d215b-9e40-4a35-b93b-51f3b0dd621a)
You can see in the screenshot that I used .warnings to list the warnings for the user, then used .check, which did not display the warnings.

**Additional context**
Red: 3.5.3
Python: 3.11.4
discord.py: 2.3.1

**Comment by killerbite95** [comment]
In your bot go to /cogs/CogManager/cogs/check/check.py and replace the line 63 to solve this.

// Original //
 await ctx.invoke(ctx.bot.get_command("warnings"), user=member)
 
 // New Line // 
 await ctx.invoke(ctx.bot.get_command("warnings"), member=member.id)

**Comment by killerbite95** [comment]
> **Describe the bug** "Check" does not show output other than what "userinfo" provides.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Use Warnings as your warning cog
> 2. Have Check installed
> 3. "check" a user with known warnings on record (.check UID or username)
> 4. Only Userinfo is displayed
> 
> **Expected behavior** When using Check I expect it to behave as described and choose between cogs to successfully display information such as warnings.
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/16052932/259413763-538d215b-9e40-4a35-b93b-51f3b0dd621a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODY0NzcsIm5iZiI6MTcxMTQ4NjE3NywicGF0aCI6Ii8xNjA1MjkzMi8yNTk0MTM3NjMtNTM4ZDIxNWItOWU0MC00YTM1LWI5M2ItNTFmM2IwZGQ2MjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDIwNDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzN2M4MjA3NzI1N2E1OGM5YzkxNWM4Yzg0N2M1NTU5NjExN2U0MmY3NzFhZTNhNDRhZjBmYTE4N2ZjMTRlMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x7tJNHFbTcxUf6qm40CeMWOSSZj2unqlXgLqTpVw1M0) You can see in the screenshot that I used .warnings to list the warnings for the user, then used .check, which did not display the warnings.
> 
> **Additional context** Red: 3.5.3 Python: 3.11.4 discord.py: 2.3.1


In your bot go to /cogs/CogManager/cogs/check/check.py and replace the line 63 to solve this.

// Original //
 await ctx.invoke(ctx.bot.get_command("warnings"), user=member)
 
 // New Line // 
 await ctx.invoke(ctx.bot.get_command("warnings"), member=member.id)

**Comment by Dav-Git** [comment]
Feel free to submit this as a PR
