### ISSUE TITLE
Roomer does not apply "Set Voice Channel Status" permission to made VCs

### ISSUE THREAD

**Issue by emshov74** [Dav-Git/Dav-Cogs#115]
**Describe the bug**
When making a voicechat with Roomer it syncs the permissions of the VC used to create it, but it does not transfer the set permissions for "Set Voice Channel Status".

**To Reproduce**
1. Make a Roomer "auto" voicechannel;
2. Set permissions for said channel, including "Set Voice Channel Status";
3. Join the "auto" VC to create a new VC;
4. Check permissions to see that the set permissions for "Set Voice Channel Status" were not carried over.

**Expected behavior**
Transfer set permissions for "Set Voice Channel Status."

**Screenshots**
Permissions in the auto room:
![image](https://github.com/Dav-Git/Dav-Cogs/assets/36211362/500aa8c8-a48c-4004-a0df-e5557fe24053)

Permissions in the cloned VC:
![image](https://github.com/Dav-Git/Dav-Cogs/assets/36211362/cb311455-628a-4763-9e02-29f13adb725f)

**Comment by Dav-Git** [comment]
This is most likely an issue with the underlying library. In theory, the permissions should just carry over from the Starter-Channel. I'm closing this issue because there has been a new dpy release since.

Feel free to reopen in case this remains an issue and I will investigate further.
