### ISSUE TITLE
[ticketer] Using emote reactions

### ISSUE THREAD

**Issue by rex2630** [Dav-Git/Dav-Cogs#36]
Hi, can u please add emote reactions for example for opening and closing tickets?
![image](https://user-images.githubusercontent.com/30006554/82826430-6b99e500-9ead-11ea-9e63-eb58b9357bd2.png)
![image](https://user-images.githubusercontent.com/30006554/82826450-781e3d80-9ead-11ea-9e32-73c3bb6d5a13.png)

**Comment by Dav-Git** [comment]
This cog is designed to be used with commands and will remain like that. Using reactions comes with a bunch of problems I'd rather avoid. Feel free to try this yourself on a fork. I will not be officially adding reaction support though.
