### ISSUE TITLE
Suggestion: Temporary Nicknames

### ISSUE THREAD

**Issue by ibigfire** [Dav-Git/Dav-Cogs#41]
It can currently be done via the scheduler cog, I know, but it would be neat to be able to set nicknames to last for a certain amount of time all with the one forcenick cog.  So you could, for example, set the person's nickname to "Birthday Boy" for specifically just a day, and then have it automatically revert to what it was when you first used the forcenick command.

I completely understand if you decide that's not within the scope of your intention for the cog though, was just an idea.  Thanks for making it in the first place, pretty handy regardless!  ^_^

**Comment by Dav-Git** [comment]
Hey @ibigfire thank you for your suggestion. Have you tried the bday cog? I always felt like just moving that Role relatively high on the role list and giving it a distinct color is better than a temp nickname.

If I can think of something relatively easy to do this I will try to implement it.

**Comment by ibigfire** [comment]
Ah yeah, the role does work for b-days.  That was possibly a bad example given you already have a cog for that haha.  But I realize now after some use that the forcenick cog works different than I was thinking anyway.  I thought it would let me set a nickname for a person via command, not have one specific default nickname that I can change users to.

So I was thinking like, I could via a bot command change one person to be named "Nice" and another person to be "Naughty", or any other name whatever for whatever is applicable to the current situation.  And then have it switch back after a few days or whatnot either via the scheduler cog or a built in command if it got implemented.

So I think I'm maybe looking for a slightly different use case than intended, which is totally fair.

**Comment by Dav-Git** [comment]
I intend to keep forcenick as lightweight as possible. These all sound great for a more elaborate nickname toolkit though.

Thanks for the suggestion.
