### ISSUE TITLE
Error mcwhitelister (to many users on list)

### ISSUE THREAD

**Issue by Nieczysty** [Dav-Git/Dav-Cogs#54]
Error mcwhitelister (to many users on list)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: Must be 1024 or fewer in length.

**Comment by Dav-Git** [comment]
Hey, how many users do you have on your whitelist? What command did you use to get this error?

**Comment by Nieczysty** [comment]
Command: whitelister list
On whitelist i have right now 90 users

**Comment by Dav-Git** [comment]
Thanks, I'll get a fix out as soon as I can
