### ISSUE TITLE
[nicknamer]Looping nicks

### ISSUE THREAD

**Issue by kablekompany** [Dav-Git/Dav-Cogs#55]
Action:
`[p]freezenick <user> nickname` on user a second time (after user nick has been frozen)

Expected:
Error from bot indicating user already froze, or removal of previously frozen nickname from figs

Result:
Bot turns user.nick back and forth between both frozen nicknames in configs. Enters the ID into the config a second time with the new nickname to freeze, leaving the old one.

Line referencing:
https://github.com/Dav-Git/Dav-Cogs/blob/4fa22ee033624f38998e420c3d65452d28d1d5ff/nicknamer/nicknamer.py#L173

Picture for reference:
![Picture](https://kableko.s3-us-east-2.amazonaws.com/headwaters-scuttering-pharyngemphraxis-hypereutectoid.png)

I hope this issue template is suitable. Great cog collection here!

**Comment by Dav-Git** [comment]
Thanks for catching this, if you want to, feel free to open a PR. I will most likely get to it next week at the earliest if you don't want to try your hand on it :)
