### ISSUE TITLE
[Supporter] whole cog is gone

### ISSUE THREAD

**Issue by theMisteryDE** [Dav-Git/Dav-Cogs#57]
After my Bot updated just 50 minutes ago, the Supporter cog wouldn't load anymore. And I can't even find it anymore in your Repo.

Traceback:

> Exception during loading of cog
> Traceback (most recent call last):
>   File "/root/redenv/lib/python3.8/site-packages/redbot/core/core_commands.py", line 119, in _load
>     await bot.load_extension(spec)
>   File "/root/redenv/lib/python3.8/site-packages/redbot/core/bot.py", line 929, in load_extension
>     lib = spec.loader.load_module()
>   File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
>   File "<frozen importlib._bootstrap_external>", line 962, in load_module
>   File "<frozen importlib._bootstrap_external>", line 787, in load_module
>   File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
>   File "<frozen importlib._bootstrap>", line 702, in _load
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/root/.local/share/Red-DiscordBot/data/Lady_Red/cogs/CogManager/cogs/supporter/__init__.py", line 6, in <module>
>     __red_end_user_data_statement__ = json.load(fp)["end_user_data_statement"]
> KeyError: 'end_user_data_statement'

**Comment by jacobactual** [comment]
He removed it or hidden it from the public and from Red instances this morning at 11:38am EST. If you're in the Cog Support server, you can view the **#new-cogs** channel. Here's an image from the channel:

![image](https://i.imgur.com/3aculny.png)

**Comment by theMisteryDE** [comment]
I have seen this Post, but since I couldn't find any clue why it is gone, but future plans for the cog, I thought it might be better to report it. Guessed could be an accident.
Well, I hope so. Liked the way it worked and just set it up a couple days ago.

**Comment by infamous-jacob** [comment]
Its only an expansion of his Ticketer cog, which you can only have one loaded at a time. If you haven't tried his Ticketer cog before, I suggest you do. I've used both and I've seen no differences between the two. I could be wrong though on that front.

**Comment by theMisteryDE** [comment]
Never tried Ticketer, direct to Supporter. Used Kennys Tickets before

**Comment by Dav-Git** [comment]
Yeah I would prefer if you use Ticketer. Supporter just turned into a bunched up mess over time and I'm dropping official support. If you want to keep your existing config and workflow supporter has moved to my unapproved repo which you can find via my GitHub account. There is some work that needs to be done on it tho so if you really need it please file an issue there. That said supporter is no longer officially supported.
