### ISSUE TITLE
[Roomer] Channel Rename

### ISSUE THREAD

**Issue by infamous-jacob** [Dav-Git/Dav-Cogs#60]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature

#### Describe your requested feature

When you click on the Channel Creation, it would name the channel with your nickname

---
*`Credits to NobodyForYou#3648` via Discord*

**Comment by Dav-Git** [comment]
Sadly this is impossible due to how channel creation works under current discord ratelimits. Only 2 channel names can be edited every 10 minutes and Im not moving members to a new channel when a new one is generated.
