### ISSUE TITLE
[Roomer] Default User Permissions

### ISSUE THREAD

**Issue by infamous-jacob** [Dav-Git/Dav-Cogs#61]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature

#### Describe your requested feature

When a user joins the voice channel to create their own, the creator of the voice channel should be given:

- View Channel
- Connect
- Speak
- Mute Members
- Deafen Members
- Use Voice Activity

**Comment by Dav-Git** [comment]
Sadly this won't work for the same reason as #60
