### ISSUE TITLE
[Exclusiveroles] unexclusive don't work

### ISSUE THREAD

**Issue by theMisteryDE** [Dav-Git/Dav-Cogs#62]
I tried this cog to help a friend to get roles rid of users the fast way. 
While testing we noticed that the unenxclusive command doesn't work.

Output is allways like this: role 1 and role 2 are not registered as exclusive roles

**Comment by Dav-Git** [comment]
@theMisteryDE

**Comment by theMisteryDE** [comment]
works now, thank you :)
