### ISSUE TITLE
[Roomer] Allow renaming the voicechannels

### ISSUE THREAD

**Issue by vlinnie** [Dav-Git/Dav-Cogs#63]
https://github.com/Dav-Git/Dav-Cogs/blob/eca79f33466e79687fb4e587ea2cfd019d3bc4c4/roomer/roomer.py#L42  

Maybe allow unique names.   
* Channel 1
* Channel 2
* Channel 3
* ....

Or have the name of the game a user is playing
And also have it in Sequence
* CSGO 1
* CSGO 2
* ....

**Comment by Dav-Git** [comment]
First one would come with quite a bit of processing overhead.

Second one is impossible due to discord ratelimits.

If you want to try your hand at option 1, go for it. I personally don't think the juice is worth the squeeze here and am not actively going to work on it for a fair bit.
