### ISSUE TITLE
botstatus streaming doesn't actually create a streaming status

### ISSUE THREAD

**Issue by zephyrkul** [Dav-Git/Dav-Cogs#65]
Streaming activities require a Twitch URL to be passed to a `url=` keyword argument to work. If no URL, or a non-twitch URL, is passed, the activity becomes a Playing activity and the purple streaming status does not appear.

(Ref for possible implementation: https://github.com/Cog-Creators/Red-DiscordBot/blob/3.4.0/redbot/core/core_commands.py#L1894-L1915)

**Comment by Dav-Git** [comment]
The way the cog was written originally makes it very hard to add features to it. Until i find the energy to rewrite the entire thing I will no longer be supporting streaming statuses. Generally, it doesn't make sense for a streaming status to be persisted across restarts, so the core functionality can be used for the duration of the stream.
