### ISSUE TITLE
Bday Cog allow admins to assign bdays to others

### ISSUE THREAD

**Issue by WormWizard0** [Dav-Git/Dav-Cogs#80]
Cog: bday

Requested Feature: Currently the bday cog allows users to assign a bday to themselves to get the autorole.  I do not know if others would be able to figure out the commands on my server, so I would like the option for admins to assign a bday to other members of the server.  The syntax could be like: [p]birthday [userID] date

**Comment by WormWizard0** [comment]
Hi there, I'm just wondering if there has been an update on this feature if there is a plan to add? If not, nbd

**Comment by Dav-Git** [comment]
The bday cog is in for an overhaul overall and your suggestion is definitely valid. I'm currently tied up with work and uni exams so it'll be a bit, but it will be coming.
