### ISSUE TITLE
Exclusive Roles Feature

### ISSUE THREAD

**Issue by milesjniemeyer** [Dav-Git/Dav-Cogs#91]
A functionality for the Reaction roles to be able to have mutually exclusive roles.

**Comment by Dav-Git** [comment]
I'm honestly not sure how to programmatically achieve mutual exclusivity... if someone has an idea, feel free to open a PR.

**Comment by milesthehighstadium** [comment]
You can't think of a way to remove a role if someone adds another? If there are 3 roles you are only able to have one at any given time and if someone adds another of those three then it removes the old one ...

**Comment by jakjakob** [comment]
Would [this](https://index.discord.red/?search=exclusiveroles) maybe work for you? @milesjniemeyer
